modulesとenvironmentに分けて実行するように変更

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -26,20 +26,20 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
+
       - name: Terraform Format
         run: terraform fmt -check -recursive
 
-  terraform-preview:
-    name: Terraform Preview
+  terraform-modules:
+    name: Terraform Modules
     runs-on: ubuntu-latest
     needs: terraform-format
     strategy:
-      max-parallel: 1
       matrix:
         folder:
-          - environment/dev
           - modules/alb
           - modules/ec2
           - modules/rds
@@ -65,28 +65,47 @@ jobs:
       - name: Terraform Validate
         run: terraform -chdir=${{ matrix.folder }} validate
 
+      - name: Terraform Plan
+        run: terraform -chdir=${{ matrix.folder }} plan
+
+  terraform-environments:
+    name: Terraform Environments
+    runs-on: ubuntu-latest
+    needs: [terraform-format, terraform-modules]
+    strategy:
+      max-parallel: 1
+      matrix:
+        folder:
+          - environment/dev
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
+          role-session-name: ${{ env.ROLE_SESSION_NAME }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Terraform Init
+        run: terraform -chdir=${{ matrix.folder }} init
+
+      - name: Terraform Validate
+        run: terraform -chdir=${{ matrix.folder }} validate
+
       - name: Create tfvars file
-        run: |
-          cat << 'EOF' > temp.tfvars
-          ${{ secrets.TFVARS_CONTENT }}
-          EOF
-
-          echo "=== Generated tfvars file ==="
-          cat temp.tfvars
-          echo "=== End of tfvars file ==="
-
-          terraform fmt temp.tfvars || echo "Format check failed, but continuing..."
+        run: echo "${{ secrets.TFVARS_CONTENT }}" > temp.tfvars
 
       - name: Terraform Plan
         run: |
           TFVARS_PATH="$(pwd)/temp.tfvars"
-          if [[ "${{ matrix.folder }}" == "environment/dev" ]]; then
-            if [ -f "$TFVARS_PATH" ]; then
-              terraform -chdir=${{ matrix.folder }} plan -var-file="$TFVARS_PATH"
-            else
-              echo "Error: tfvars file not found at $TFVARS_PATH"
-              exit 1
-            fi
+          if [ -f "$TFVARS_PATH" ]; then
+            terraform -chdir=${{ matrix.folder }} plan -var-file="$TFVARS_PATH"
           else
-            terraform -chdir=${{ matrix.folder }} plan
+            echo "Error: tfvars file not found at $TFVARS_PATH"
+            exit 1
           fi
