environment, modulesに分けてvalidateを実行

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -65,18 +65,6 @@ jobs:
       - name: Terraform Validate
         run: terraform -chdir=${{ matrix.folder }} validate
 
-      - name: Create tfvars file
-        run: echo "${{ secrets.TFVARS_CONTENT }}" | base64 -d > temp.tfvars
-      - name: Terraform Plan
-        run: |
-          TFVARS_PATH="$(pwd)/temp.tfvars"
-          if [ -f "$TFVARS_PATH" ]; then
-            terraform -chdir=${{ matrix.folder }} plan -var-file="$TFVARS_PATH"
-          else
-            echo "Error: tfvars file not found at $TFVARS_PATH"
-            exit 1
-          fi
-
   terraform-environments:
     name: Terraform Environments
     runs-on: ubuntu-latest
@@ -106,15 +94,15 @@ jobs:
       - name: Terraform Validate
         run: terraform -chdir=${{ matrix.folder }} validate
 
-      - name: Create tfvars file
-        run: echo "${{ secrets.TFVARS_CONTENT }}" > temp.tfvars
+      # - name: Create tfvars file
+      #   run: echo "${{ secrets.TFVARS_CONTENT }}" > temp.tfvars
 
-      - name: Terraform Plan
-        run: |
-          TFVARS_PATH="$(pwd)/temp.tfvars"
-          if [ -f "$TFVARS_PATH" ]; then
-            terraform -chdir=${{ matrix.folder }} plan -var-file="$TFVARS_PATH"
-          else
-            echo "Error: tfvars file not found at $TFVARS_PATH"
-            exit 1
-          fi
+      # - name: Terraform Plan
+      #   run: |
+      #     TFVARS_PATH="$(pwd)/temp.tfvars"
+      #     if [ -f "$TFVARS_PATH" ]; then
+      #       terraform -chdir=${{ matrix.folder }} plan -var-file="$TFVARS_PATH"
+      #     else
+      #       echo "Error: tfvars file not found at $TFVARS_PATH"
+      #       exit 1
+      #     fi
